const response = {
    items: [
        { term: 'cemènt', lemma: 'cemènt', frequency: 9023 },
        { term: 'aluminátni cemènt', lemma: 'aluminátni cemènt', frequency: 7646 },
        { term: 'béli cemènt', lemma: 'béli cemènt', frequency: 3183 },
        { term: 'cemènt visôke zgódnje tŕdnosti', lemma: 'cemènt visôke zgódnje tŕdnosti', frequency: 5096 },
        { term: 'cemènt z nízko hidratácijsko toplôto', lemma: 'cemènt z nízko hidratácijsko toplôto', frequency: 8468 },
        { term: 'ekspanzívni cemènt', lemma: 'ekspanzívni cemènt', frequency: 1525 },
        { term: 'hidrávlični cemènt', lemma: 'hidrávlični cemènt', frequency: 9036 },
        { term: 'hidrofóbni cemènt', lemma: 'hidrofóbni cemènt', frequency: 7425 },
        { term: 'hitrovézni cemènt', lemma: 'hitrovézni cemènt', frequency: 8029 },
        { term: 'hitrovezóči cemènt', lemma: 'hitrovezóči cemènt', frequency: 4772 },
        { term: 'méšani cemènt', lemma: 'méšani cemènt', frequency: 3233 },
        { term: 'méšani pórtlandski cemènt', lemma: 'méšani pórtlandski cemènt', frequency: 9402 },
        { term: 'metalúrški cemènt', lemma: 'metalúrški cemènt', frequency: 1249 },
        { term: 'navádni pórtlandski cemènt', lemma: 'navádni pórtlandski cemènt', frequency: 8574 },
        { term: 'normálni cemènt', lemma: 'normálni cemènt', frequency: 1501 },
        { term: 'normálnovezóči cemènt', lemma: 'normálnovezóči cemènt', frequency: 7748 },
        { term: 'počásivezóči cemènt', lemma: 'počásivezóči cemènt', frequency: 1992 },
        { term: 'pórtland cemènt', lemma: 'pórtland cemènt', frequency: 7025 },
        { term: 'pórtlandski cemènt', lemma: 'pórtlandski cemènt', frequency: 7975 },
        { term: 'pucolánski cemènt', lemma: 'pucolánski cemènt', frequency: 5747 },
        { term: 'sulfátnoodpórni cemènt', lemma: 'sulfátnoodpórni cemènt', frequency: 4074 },
        { term: 'súpersulfátni cemènt', lemma: 'súpersulfátni cemènt', frequency: 1389 },
        { term: 'vodoodpórni cemènt', lemma: 'vodoodpórni cemènt', frequency: 1986 },
        { term: 'žlíndrin cemènt', lemma: 'žlíndrin cemènt', frequency: 6759 },
    ],
    total: 24,
    offset: 0,
};

export default response;